from threading import Thread

l = [1,2,3]

class MyThread(Thread):
    a = 10
    b = 20
    def run(self):
        for item in l:
            print("executed own thread")
    temp = a +b

t1 = MyThread()
t1.start()
print(t1.temp)

# advantage of using own thread - can access data generated by thread
